### PR TITLE
Repo Refactor

### LINKED ISSUE #268: measure_operator_cost not implemented for op Cache_103
I installed FlexFlow from the source code. When I test moe in examples/cpp/mixture-of-experts folder, it gave me the following error: `measure_operator_cost not implemented for op Cache_103  (type 25). Please report this issue to the FlexFlow developers.`

### LINKED ISSUE #271: Verify C++11 compatibility in Unity branch

### LINKED ISSUE #302: Convert `ParallelTensor` to not be a typedef'ed pointer

### LINKED ISSUE #303: Pull kernel functions out of operator classes
Following https://github.com/lockshaw/FlexFlow/blob/feat/candle_split/include/flexflow/ops/linear_kernels.h

See discussion at https://github.com/flexflow/FlexFlow/pull/298#discussion_r956470999

### LINKED ISSUE #304: Replace `layer_guid` with separate `get_tensor` handling

### LINKED ISSUE #403: Add ability to store and load strategies to and from a file

### LINKED ISSUE #424: Add a new operator 'stop_gradient'
This operator exists for JAX. Any of the operands as an input to the stop_gradient function, do not calculate gradients with respect to their inputs.

### LINKED ISSUE #440: Kernel refactor for `ElementUnary`

### LINKED ISSUE #445: Kernel refactor for `LayerNorm`

### LINKED ISSUE #446: Kernel refactor for `MultiHeadAttention`

### LINKED ISSUE #513: Separate runtime and optimizer into separate binaries
Requires #403

### LINKED ISSUE #569: Unify `fused.cpp` and `fused.cu`
These files are abstracted away from the hardware differences by the operators, so I see little reason to have both of them around. They should be unified so they don't go out of sync anymore.

### LINKED ISSUE #583: Refactor out Legion code shared between operators
There's a pretty substantial amount of rather opaque legion code in each of the operators. It seems unlikely to me that there isn't significant redundancy between them. We should reduce this redundancy

_Originally posted by @lockshaw in https://github.com/flexflow/FlexFlow/pull/576#discussion_r1082161115_

### LINKED ISSUE #752: Support reduce_mean
See #676 for an initial implementation

### PR DESCRIPTION
**Pull request by lockshaw**
**Description of changes:**

- Divide FlexFlow's C++ code into `compiler`, `runtime`, `op-attrs`, `kernels`, `pcg`, `utils`, and `substitutions` libraries. Only `runtime` has an explicit legion dependency
- Separate out computation graph construction (now `ModelSpec`) from PCG management (`FFModel`)
- Move `Tensor`, `ParallelTensor`, `Layer`, etc. construction into factory classes (`TensorManager`, `ParallelTensorManager`, `LayerManager`)
- Refactor the computation graph to rely on `utils`'s labelled graphs
- Add safer and more concise `task_spec` interface for legion tasks (see https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/runtime/src/task_spec/README.md for documentation)
- Add infrastructure to more easily write reduced precision kernels (i.e. `DataTypeDispatch*`)
- Add well-defined interface to optimizing via `compiler`
- Add extensible and statically checked legion task argument serialization interface
- Refactor `Tensor` and `Layer` to be immutable
- Add type-safe typedefs for various guid types (`tensor_guid_t`, `LayerID`, `parallel_tensor_guid_t`, etc.)
- Implement new graph library in `utils`, including new open graph types (see https://github.com/flexflow/FlexFlow/blob/repo-refactor/lib/utils/include/utils/graph/README.md for documentation)
- Implement new generic container functions (`containers.h`) in `utils`
- Add infrastructure for simplifying POD types (`visit_struct`)
- Add runtime-checked stack-allocated stl-like data structures (`stack_vector`, `stack_map`, `stack_string`)
- Reimplement `cmake` code to be more modern and concise
- Move to `doctest` and `rapidcheck`, also add dependencies on `tl::expected`, `fmt`, `spdlog` 

Remaining Todos:
- [ ] Issue #346 
- [ ] Issue #404 
- [ ] Issue #405 
- [ ] Issue #534
- [ ] Issue #819 

**Related Issues:**

Linked Issues:
- Issue #351 
- Issue #408 

Issues closed by this PR:
- Closes #440 
- Closes #446
- Closes #445
- Closes #302 
- Closes #583 
- Closes #513 
- Closes #303
- Closes #569
- Closes #403 
- Closes #752 
- Closes #268
- Closes #271 
- Closes #304 
- Closes #424 

**Before merging:**

- [ ] Did you update the [flexflow-third-party](https://github.com/flexflow/flexflow-third-party) repo, if modifying any of the Cmake files, the build configs, or the submodules?

- - -
This change is [Reviewable](https://reviewable.io/reviews/flexflow/FlexFlow/622)

### CODE REVIEW

**Comment by lockshaw** [comment]
@virena @wmdi @eric-zheng

**Comment by lockshaw** [comment]
@virena Does this fix #455?

**Comment by lockshaw** [comment]
@virena @williamberman Approximate PR changelist added!

File: lib/runtime/op_task_spec.cc [hunk 1]
```diff
@@ -8,11 +8,11 @@ using namespace Legion;
 
 namespace FlexFlow {
 
-bool TensorSpec::operator==(TensorSpec const &other) const {
+bool OpTensorSpec::operator==(OpTensorSpec const &other) const {
```
Comment (lockshaw) [inline lib/runtime/op_task_spec.cc:11]: Unnecessary due to `visitable_cmp`

File: lib/runtime/src/ops/dropout.cc [hunk 2]
```diff
@@ -112,177 +161,216 @@ Dropout::Dropout(FFModel &model,
...
+//                                                     0 /*projection id*/,
+//                                                     WRITE_ONLY,
+//                                                     EXCLUSIVE,
+//                                                     outputs[0]->region));
+//   launcher.add_field(1, FID_DATA);
+//   runtime->execute_index_space(ctx, launcher);
+// }
 
-void Dropout::forward_task(Task const *task,
+static void forward_task(Task const *task,
```
Comment (lockshaw) [inline lib/runtime/src/ops/dropout.cc:255]: See the new `task` vs `task_impl` change

File: lib/runtime/test/src/test_serialization.cc [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+#include "legion/legion_utilities.h"
+#include "serialization.h"
+#include "op-attrs/ops/linear.h"
+#include "op-attrs/ops/conv_2d.h"
+#include "op-attrs/ffconst.h"
+
+using namespace FlexFlow;
+
+TEST_CASE("Serialization") {
+  Legion::Serializer sez ();
```
Comment (lockshaw) [inline lib/runtime/test/src/test_serialization.cc:11]: No parentheses needed here

File: lib/runtime/test/src/test_serialization.cc [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+  Legion::Deserializer dez (sez.get_buffer(), sez.get_buffer_size());
+
+  /* Linear */
+  LinearAttrs linear_attrs ();
+  Serialization<LinearAttrs> linear;
```
Comment (lockshaw) [inline lib/runtime/test/src/test_serialization.cc:16]: You can just use `ff_task_serialize` here

File: lib/runtime/test/src/test_task_spec.cc [hunk 5]
```diff
@@ -22,4 +22,21 @@ TEST_CASE("OpTaskSignature") {
...
+  binding.bind(1, input_tensor(1));
+  binding.bind(2, input_tensor(2));
+
+  OpTaskBinding bwd = infer_bwd_binding(fwd);
+
+  OpTaskBinding correct_bwd;
+
+  correct_bwd.bind(0);
+  correct_bwd.bind_grad(0);
+}
```
Comment (lockshaw) [inline lib/runtime/test/src/test_task_spec.cc:42]: Missing a correctness check
